### ISSUE TITLE
每次渲染出来比例都不一样？

### ISSUE THREAD

**Issue by bruce-zhang932** [Teemwu/doughnut#1]
![image](https://user-images.githubusercontent.com/11385973/129320104-e114e73e-c2fd-4e32-ae2d-5bf57e2d5ff9.png)
您好看了您的博文之后想把他用在项目中，我的项目用的是Taro-react 我改了改，但是每次刷新渲染出来的比例都不一样？
home.tsx
`<Annular value={[20, 30, 15, 35]} is2D={true && true} duration={800} unit='%'  />`

annular.tsx
`import { PureComponent } from 'react'
import { View, Canvas } from "@tarojs/components"
import Taro, { createCanvasContext, createSelectorQuery, getSystemInfoSync, nextTick } from '@tarojs/taro'

// import './index.less'

export default class Annular extends PureComponent<any, any>{

  readonly state = {
    r: 65,
    centerPoint: { x: 100, y: 100 },
    textPoints: [],
    activeIndex: -1,
    angles: [],
    timer: null,
    canvas: null,
    ctx: null,
    intervel: 16,
    border: 32,
    activeBorder: 36,
    duration: 600,
    borderBgColor: '#efefef',
    borderColors: ['#399DED', '#7480EC', '#E99137', '#FE698D'],
    tipsColor: '#ffffff',
    tipsSize: 8,
    text: ['已退回', '进行中', '待审核', '已完成']
  }

  componentDidMount() {
    const { text } = this.state
    Taro.eventCenter.once(Taro.Current.router?.onReady as any, () => {
      this.initCanvas()
   })
  }

  easeInQuadratic = (currentTime, startValue, changeValue, duration) => {
    currentTime /= duration
    return changeValue * currentTime * currentTime + startValue
  }

  requestAnimationFrame = (callback, lastTime = 0) => {
    const { canvas, intervel } = this.state
    const { is2D } = this.props
    const start = new Date().getTime()
    if (is2D && canvas && (canvas as any).requestAnimationFrame) {
      (this as any).timer = (canvas as any).requestAnimationFrame(() => {
        const now = new Date().getTime()
        lastTime += now - start
        callback(lastTime)
      })
    } else {
      (this as any).timer = setTimeout(() => {
        const now = new Date().getTime()
        lastTime += now - start
        callback(lastTime)
      }, intervel)
    }
  }

  cancelAnimationFrame() {
    const { canvas } = this.state
    const { is2D } = this.props
    if (is2D && canvas && (canvas as any).cancelAnimationFrame) {
      (canvas as any).cancelAnimationFrame((this as any).timer)
    } else {
      clearTimeout((this as any).timer)
    }
  }

  renderText = () => {
    return false
  }

  canvasTouch(e) {
    const { centerPoint, r, angles, border, activeIndex } = this.state
    const { x, y } = e.changedTouches[0]
    const { x: _x, y: _y } = centerPoint
    // 两点距离
    const len = Math.sqrt(Math.pow(_y - y, 2) + Math.pow(_x - x, 2))
    const borderHalf = border / 2
    // 是否在弧线内
    const isInRing = len > r - borderHalf && len < r + borderHalf
    let current = activeIndex
    if (isInRing) {
      // 获取圆心角
      let angle = Math.atan2(y - _y, x - _x)
      // 判断弧度是否为负，为负时需要转正
      angle = angle > 0 ? angle : 2 * Math.PI + angle
      angles.some((item, index) => {
        // 是否在弧度内
        if (item > angle) {
          current = index
          return true
        }
      })
    } else {
      current = -1
    }

    this.setState({
      activeIndex: current
    })
    this.init()
  }

  animate = () => {
    const { border, ctx, duration, borderBgColor, timer } = this.state
    const { is2D, value, active } = this.props
    if (ctx) {
      if (timer) this.cancelAnimationFrame()
      const callback = lastTime => {
        (ctx as any).clearRect(0, 0, 200, 200)
        lastTime = lastTime >= duration ? duration : lastTime
        if (lastTime === duration) {
          this.cancelAnimationFrame()
          this.setState({
            activeIndex: active
          }, () => {
            this.init()
          })
          return
        }
        const ratios = value.map(i => this.easeInQuadratic(lastTime, 0, i, duration))
        this.drawArc(0, 2 * Math.PI, border, borderBgColor)
        this.drawArcs(ratios)
        if (!is2D) (ctx as any).draw()
        this.requestAnimationFrame(callback, lastTime)
      }
      this.requestAnimationFrame(callback)
    } else {
      this.initCanvas()
    }
  }

  drawCenter = () => {
    const { r, border, centerPoint, ctx } = this.state
    const { is2D } = this.props
    const { x, y } = centerPoint as any
    /**画圆遮挡 */
    (ctx as any).beginPath();
    (ctx as any).arc(x, y, r - border / 2, 0, 2 * Math.PI);
    (ctx as any).fillStyle = '#ffffff';
    (ctx as any).fill();
    (ctx as any).closePath();
    const fontSize = 12;
    if (is2D) {
      (ctx as any).font = fontSize;
      (ctx as any).fillStyle = '#203e62';
    } else {
      (ctx as any).setFontSize(fontSize);
      (ctx as any).setFillStyle('#203e62');
    }
    /**画圆中心的文字 */
    const { width } = (ctx as any).measureText('结果统计');
    (ctx as any).fillText('结果统计', x - width / 2, y + fontSize / 2);
  }

  drawText = () => {
    const { textPoints, ctx, tipsColor, tipsSize } = this.state
    const { is2D, unit } = this.props
    if (is2D) {
      (ctx as any).font = tipsSize;
      (ctx as any).fillStyle = tipsColor
    } else {
      (ctx as any).setFontSize(tipsSize)
      (ctx as any).setFillStyle(tipsColor)
    }
    textPoints.forEach((item:any) => {
      if (item.value > 0) {
        const { width } = (ctx as any).measureText(`${item.value}${unit}`)
        const x = item.x - width / 2
        const y = item.y + tipsSize / 2
        const text = `${item.value}${unit}`;
        (ctx as any).fillText(text, x, y)
      }
    })
  }

  drawArc = (sAngle, eAngle, border, color) => {
    const { r, centerPoint, ctx } = this.state;
    const { x, y } = centerPoint;
    (ctx as any).beginPath();
    (ctx as any).lineWidth = border;
    (ctx as any).strokeStyle = color;
    (ctx as any).arc(x, y, r, sAngle, eAngle, false);
    (ctx as any).stroke();
    (ctx as any).closePath();
  }

  drawArcs(ratios) {
    const { r, activeIndex, borderColors, border, activeBorder, centerPoint} = this.state
    const { x: _x, y: _y } = centerPoint
    const _angles = []
    const _textPoints = []
    let sAngle = 0
    ratios.forEach((item, index) => {
      const angle = (item * Math.PI) / 50
      const eAngle = sAngle + angle
      const _activeBorder = activeIndex === index && ratios.length > 1 ? (activeBorder - border) * 2 : 0
      const _border = border + _activeBorder
      const _color = borderColors[index]
      this.drawArc(sAngle, eAngle, _border, _color)
      // 要绘制文本所在点的弧度
      const _angle = sAngle + angle / 2
      const x = _x + r * Math.cos(_angle)
      const y = _y + r * Math.sin(_angle)
      _textPoints.push({ x, y, value: item } as never)
      _angles.push(eAngle as never)
      sAngle = eAngle
    })

    this.setState({
      angles: _angles,
      textPoints: _textPoints
    })
  }

  init = () => {
    const { border, ctx, } = this.state
    const { is2D, value } = this.props;
    (ctx as any).clearRect(0, 0, 200, 200)
    /**画环形图的背景 */
    this.drawArc(0, 2 * Math.PI, border, '#efefef')
    this.drawArcs(value)
    this.drawText()
    this.drawCenter()
    if (!is2D) (ctx as any).draw()
  }

  initCanvas() {
    const { is2D } = this.props
    if (is2D) {
      createSelectorQuery()
        .select('#canvas')
        .fields({ node: true, size: true })
        .exec(res => {
          const canvas = res[0].node
          const _ctx = canvas.getContext('2d')
          const dpr = getSystemInfoSync().pixelRatio
          canvas.width = res[0].width * dpr
          canvas.height = res[0].height * dpr
          _ctx.scale(dpr, dpr)
          this.setState({
            canvas,
            ctx: _ctx
          }, () => {
            this.animate()
          })
        })
    } else {
      this.setState({
        ctx: createCanvasContext('canvas')
      }, () => {
        this.animate()
      })
    }
  }

  render() {
    let { is2D } = this.props
    return (
      <View className='annular-wrapper'>
        <Canvas style={{width: '600rpx',height: '400rpx'}} id='canvas' className='annular-canvas' canvasId='canvas' type={is2D ? '2d' : ''} onTouchStart={this.canvasTouch} />
      </View>
    )
  }
}`

**Comment by Teemwu** [comment]
大概看了下，进行如下修改后貌似可以正常显示：
```javascript
// 省略...
                if (lastTime === duration) {
                    this.cancelAnimationFrame()
                    // this.setState({
                    //     activeIndex: active
                    // }, () => {
                    //     this.init()
                    // })
                    this.setState({
                        activeIndex: active
                    })
                    this.init()
                    return
                }
// 省略...
```

**Comment by bruce-zhang932** [comment]
![image](https://user-images.githubusercontent.com/11385973/129432327-be4770be-1fb5-4c9e-b7dc-def11523049e.png)
您好，我看文章案例里有标题A:B，这是在哪里设置的？

**Comment by Teemwu** [comment]
抱歉，之前忘了提交代码，现已更新，使用 `renderText` 属性可自定义显示内容。

**Comment by bruce-zhang932** [comment]
![image](https://user-images.githubusercontent.com/11385973/129466583-a21d5829-efa8-478c-930e-5d3fc47bcbe0.png)
设置居中文字的文字大小不起作用？

**Comment by Teemwu** [comment]
这边设置能正常改变，并未复现问题。由于和标题偏离，暂时关闭此 issue 了，后面还有其它问题请重新开个 issue 。
