### ISSUE TITLE
当value数据发生变化时环形图该如何重新渲染？

### ISSUE THREAD

**Issue by bruce-zhang932** [Teemwu/doughnut#2]
博主您好，我把代码改成了taro-react形式的，我这有个需求是要动态的选择数据，
当父组件传来的value数据发生变化时环形图该如何重新渲染呢？
`componentDidMount() {
    setTimeout(() => {
      this.initCanvas()
    }, 500)
  }
`
`initCanvas() {
    const { is2D, ids } = this.props
    if (is2D) {
      createSelectorQuery()
        .select(`#${ids}`)
        .fields({ node: true, size: true })
        .exec(res => {
          console.log('res ~ ', res)
          const canvas = res[0].node
          const _ctx = canvas.getContext('2d')
          const dpr = getSystemInfoSync().pixelRatio
          canvas.width = res[0].width * dpr
          canvas.height = res[0].height * dpr
          _ctx.scale(dpr, dpr)
          this.setState({
            canvas,
            ctx: _ctx
          }, () => {
            this.animate()
          })
        })
    } else {
      this.setState({
        ctx: createCanvasContext('canvas')
      }, () => {
        this.animate()
      })
    }
  }`

**Comment by Teemwu** [comment]
taro-vue 的话直接改变传入的 value 值，环形图就会自动重新渲染，taro-react 应该也差不多，周末有空我试着改成 react 版本吧

**Comment by bruce-zhang932** [comment]
@Teemwu 您好，我看您会去watch监听value的变化，然后执行this.animate。react的话我不知道该如何去处理。我看有个componentWillReceiveProps的方法去监听父组件值的变化，但是taro好像马上就废弃这个方法了
![image](https://user-images.githubusercontent.com/11385973/131949665-00fad3ba-f83c-467d-920c-026b99719117.png)

**Comment by Teemwu** [comment]
不好意思，平时不怎么写 react，大概改了下能正常跑，写法如有问题请指正哈，[代码地址](https://github.com/Teemwu/doughnut-react/tree/main/src/components)。

**Comment by Teemwu** [comment]
react 的 `componentWillReceiveProps` 查了下是要废弃，可用 `getDerivedStateFromProps` 来代替，暂时没试。

试了下 react 的 hooks 写法使用 `useEffect` 是可以监听父组件值变化的。

react 的 class 写法使用 `componentWillUpdate` 则可监听 props 的变化。

**Comment by bruce-zhang932** [comment]
@Teemwu 非常感谢
