### ISSUE TITLE
环形图在安卓手机上有时会出现闪退的情况该从哪块去优化？

### ISSUE THREAD

**Issue by bruce-zhang932** [Teemwu/doughnut#3]
这个环形图嵌到我的小程序里后，在安卓手机上有时会出现闪退的情况（随机性，概率在5%左右），问题会出在哪？我该从那些方面着手去优化？

**Comment by Teemwu** [comment]
改变动画时常会有影响么？我用安卓手机暂时没有复现

**Comment by Teemwu** [comment]
查看了下某些情况下 canvas 初始化会失败，但不会出现闪退现象，使用 Taro.nextTick 延迟执行 canvas 的初始化试试看，不确定是这个问题。https://github.com/Teemwu/doughnut/blob/b8809bc4db708cdfc9a4bc03ea25f8fb8a1bef8d/src/components/doughnut/index.vue#L352-L358

**Comment by bruce-zhang932** [comment]
您好，应该不是初始化的问题，我看到环形图动画走到快结束的时候，突然停下小程序就闪退了。我怀疑事动画的缘故，怎样让他没有这个动画呢？

**Comment by Teemwu** [comment]
可否提供下复现的例子或者导致闪退时所传入的百分比数组？

需要关闭动画将 animate 方法修改成如下即可：
```javascript
    animate() {
      const { ctx, active } = this
      if (ctx) {
          this.activeIndex = active
          this.init()
      } else {
          this.initCanvas()
      }
    },
```
